version: '3'
services:

  dcp-server:
    build: server
    #image: wut/server
    environment:
      SERVER_IP: 10.0.1.11
      CLIENT_IP: 10.0.2.10
    ports:
    - "8000:8000"
    privileged: true
  
  dcp-client:
    build: client
    #image: wut/client
    environment:
      SERVER_IP: 10.0.1.11
      CLIENT_IP: 10.0.2.10
      FILE_NAME: musk.png
    ports:
    - "8000:8000"
    privileged: true
