version: '3'
services:

  dcp-server:
    build: server
    #image: wut/server
    environment:
      SERVER_IP: 192.168.10.11
      CLIENT_IP: 192.168.10.12
    ports:
    - "8000:8000"
    privileged: true
  
  dcp-client:
    build: client
    #image: wut/client
    environment:
      SERVER_IP: 192.168.10.11
      CLIENT_IP: 192.168.10.12
      FILE_NAME: musk.png
    ports:
    - "9000:9000"
    privileged: true
